language: cpp
node_js: 
  - "8.3"
os:
  - windows
matrix:
  include:
    - os: windows
      env:
        - MSBUILD_PATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"
install: 
    - cmd.exe /C .travis/install.bat
script:
   - export PATH=$MSBUILD_PATH:$PATH
   # - MSBuild.exe ProxyServer/ProxyServer.sln -t:Rebuild -p:Configuration=Release
